# -*- coding: utf-8 -*-
"""password_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19lOAVyZKq6I-TVRlyv83nhZc1_roI1A4
"""

import random
import string

def generate_password(length):
    # Characters to use in password
    letters = string.ascii_letters
    digits = string.digits
    symbols = string.punctuation

    all_characters = letters + digits + symbols

    # Generate password
    password = ''.join(random.choice(all_characters) for i in range(length))

    return password

# Take user input
length = int(input("Enter password length: "))

# Generate and display password
password = generate_password(length)
print("Your generated password is:", password)